In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Data/EPL_1617.csv")

In [47]:
season = df.iloc[:,1:11]

In [44]:
columns = ['Date', 'HomeTeam', 'AwayTeam', 
           'FullTimeHomeGoals', 'FullTimeAwayGoals', 'FullTimeResults', 
           'HalfTimeHomeGoals', 'HalfTimeAwayGoals', 'HalfTimeResults', 'Referee']

In [45]:
#season.columns = columns

In [54]:
season.HomeTeam.unique()

array(['Burnley', 'Crystal Palace', 'Everton', 'Hull', 'Man City',
       'Middlesbrough', 'Southampton', 'Arsenal', 'Bournemouth', 'Chelsea',
       'Man United', 'Leicester', 'Stoke', 'Swansea', 'Tottenham',
       'Watford', 'West Brom', 'Sunderland', 'West Ham', 'Liverpool'], dtype=object)

In [56]:
for i in season.HomeTeam.unique():
    df_%s %i

NameError: name 'df_' is not defined

In [48]:
arsenal_1617 = season[(season["HomeTeam"] == 'Arsenal') | (season['AwayTeam'] == 'Arsenal')]

In [49]:
arsenal_1617

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee
7,14/08/16,Arsenal,Liverpool,3,4,A,1,1,D,M Oliver
12,20/08/16,Leicester,Arsenal,0,0,D,0,0,D,M Clattenburg
27,27/08/16,Watford,Arsenal,1,3,A,0,3,A,K Friend
30,10/09/16,Arsenal,Southampton,2,1,H,1,1,D,R Madley
42,17/09/16,Hull,Arsenal,1,4,A,0,1,A,R East
50,24/09/16,Arsenal,Chelsea,3,0,H,3,0,H,M Oliver
66,02/10/16,Burnley,Arsenal,0,1,A,0,0,D,C Pawson
70,15/10/16,Arsenal,Swansea,3,2,H,2,1,H,J Moss
80,22/10/16,Arsenal,Middlesbrough,0,0,D,0,0,D,M Dean
93,29/10/16,Sunderland,Arsenal,1,4,A,0,1,A,M Atkinson
105,06/11/16,Arsenal,Tottenham,1,1,D,1,0,H,M Clattenburg
112,19/11/16,Man United,Arsenal,1,1,D,0,0,D,A Marriner
126,27/11/16,Arsenal,Bournemouth,3,1,H,1,1,D,M Jones
136,03/12/16,West Ham,Arsenal,1,5,A,0,1,A,C Pawson
140,10/12/16,Arsenal,Stoke,3,1,H,1,1,D,L Mason
151,13/12/16,Everton,Arsenal,2,1,H,1,1,D,M Clattenburg
167,18/12/16,Man City,Arsenal,2,1,H,0,1,A,M Atkinson
170,26/12/16,Arsenal,West Brom,1,0,H,0,0,D,N Swarbrick
188,01/01/17,Arsenal,Crystal Palace,2,0,H,1,0,H,A Marriner
196,03/01/17,Bournemouth,Arsenal,3,3,D,2,0,H,M Oliver
204,14/01/17,Swansea,Arsenal,0,4,A,0,1,A,M Jones
217,22/01/17,Arsenal,Burnley,2,1,H,0,0,D,J Moss
220,31/01/17,Arsenal,Watford,1,2,A,0,2,A,A Marriner
230,04/02/17,Chelsea,Arsenal,3,1,H,1,0,H,M Atkinson
240,11/02/17,Arsenal,Hull,2,0,H,1,0,H,M Clattenburg
259,04/03/17,Liverpool,Arsenal,3,1,H,2,0,H,R Madley
278,18/03/17,West Brom,Arsenal,3,1,H,1,1,D,N Swarbrick

In [50]:
def calc_points_and_goals(df):
    for row in df:
        print row

In [51]:
calc_points_and_goals(arsenal_1617)

Date
HomeTeam
AwayTeam
FTHG
FTAG
FTR
HTHG
HTAG
HTR
Referee

In [ ]:
for i in