In [58]:
import pandas as pd
pd.options.display.max_columns = 999

# Creating the teams dataframe

In [59]:
##Define the object for the season team
class MyDf:
    def __init__(self, mydf):
        self.df = mydf

In [60]:
df = pd.read_csv("../Data/EPL_1617.csv")

In [61]:
season = df.iloc[:,1:11]

In [62]:
teams=season.HomeTeam.unique()

In [63]:
allteamsresults=[]
for i in teams:
    path=pd.DataFrame()            
    path = season[(season["HomeTeam"] == i) | (season['AwayTeam'] == i )] 
    allteamsresults.append(MyDf(path))

## Now allteameasresults has memorized all the results of the season per teams. You can access to each team results with the team index. The position of the team in the list "teams" will give you the index of the team results in the dataframe allteamsresults.

In [64]:
teams

array(['Burnley', 'Crystal Palace', 'Everton', 'Hull', 'Man City',
       'Middlesbrough', 'Southampton', 'Arsenal', 'Bournemouth', 'Chelsea',
       'Man United', 'Leicester', 'Stoke', 'Swansea', 'Tottenham',
       'Watford', 'West Brom', 'Sunderland', 'West Ham', 'Liverpool'], dtype=object)

the index of Arsenal is 7

In [65]:
allteamsresults[7].df.head(n=2)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee
7,14/08/16,Arsenal,Liverpool,3,4,A,1,1,D,M Oliver
12,20/08/16,Leicester,Arsenal,0,0,D,0,0,D,M Clattenburg

## Now, lets calculate some other features

## 1) Goal scored and received - home and away.
### We will shift of one match back each calculation, which means, each row will have the present match and the statistics goals scored up to that day (before the match).

In [66]:
def calculate_for_team_i(ALL_TEAM,team_lists,team_index):
    
    #create the lists for goals
    Goal_scored_home=[]
    Goal_received_home=[]
    Goal_scored_away=[]
    Goal_received_away=[]
    
    #create the list for averages goals
    Av_Goal_scored_home=[]
    Av_Goal_received_home=[]
    Av_Goal_scored_away=[]
    Av_Goal_received_away=[]
    
    
    #create the list points
    Point_home=[]
    Point_away=[]
    
    #create the list for average Points
    Av_Point_home=[]
    Av_Point_away=[]
    
    
    #create the index
    k=1

    #append day 1 that is empty
    Goal_scored_home.append(0)
    Goal_received_home.append(0)
    Goal_scored_away.append(0)
    Goal_received_away.append(0)
    Av_Goal_scored_home.append(0)
    Av_Goal_received_home.append(0)
    Av_Goal_scored_away.append(0)
    Av_Goal_received_away.append(0)
    Point_home.append(0)
    Point_away.append(0)
    Av_Point_home.append(0)
    Av_Point_away.append(0)
    
    #create a counter
    Home=0
    Away=0
    
    #run the loop for each team
    for i in ALL_TEAM[team_index].df.index:
        
        
        #HOME
        if ALL_TEAM[team_index].df['HomeTeam'][i]==team_lists[team_index]:
            

            #goal scored and received
            Goal_scored_home.append(ALL_TEAM[team_index].df['FTHG'][i]+Goal_scored_home[k-1])
            Goal_received_home.append(ALL_TEAM[team_index].df['FTAG'][i]+Goal_received_home[k-1])
            Goal_scored_away.append(Goal_scored_away[k-1])
            Goal_received_away.append(Goal_received_away[k-1])
            
            #average
            Home=Home+1
            Av_Goal_scored_home.append(float(Goal_scored_home[k])/Home)
            Av_Goal_received_home.append(float(Goal_received_home[k])/Home)
            Av_Goal_scored_away.append(Av_Goal_scored_away[k-1])
            Av_Goal_received_away.append(Av_Goal_received_away[k-1])
            
           
            #Point winning
            if ALL_TEAM[team_index].df['FTR'][i]=='H':
                Point_home.append(3+Point_home[k-1])
                Av_Point_home.append(float(Point_home[k])/Home)
            
            #Point draw
            if ALL_TEAM[team_index].df['FTR'][i]=='D':
                Point_home.append(1+Point_home[k-1])
                Av_Point_home.append(float(Point_home[k])/Home)
                
            #Point lost
            if ALL_TEAM[team_index].df['FTR'][i]=='A':
                Point_home.append(0+Point_home[k-1])
                Av_Point_home.append(float(Point_home[k])/Home)
              
            
            Point_away.append(Point_away[k-1])
            Av_Point_away.append(Av_Point_away[k-1])
            

            
        
        #AWAY
        if ALL_TEAM[team_index].df['HomeTeam'][i]!=team_lists[team_index]:
            
            
            Goal_scored_away.append(ALL_TEAM[team_index].df['FTAG'][i]+Goal_scored_away[k-1])
            Goal_received_away.append(ALL_TEAM[team_index].df['FTHG'][i]+Goal_received_away[k-1])
            Goal_scored_home.append(Goal_scored_home[k-1])
            Goal_received_home.append(Goal_received_home[k-1])
            
            #average
            Away=Away+1
            Av_Goal_scored_away.append(float(Goal_scored_away[k])/Away)
            Av_Goal_received_away.append(float(Goal_received_away[k])/Away)
            Av_Goal_scored_home.append(Av_Goal_scored_home[k-1])
            Av_Goal_received_home.append(Av_Goal_received_home[k-1])
            
            #Point winning
            if ALL_TEAM[team_index].df['FTR'][i]=='A':
                Point_away.append(3+Point_away[k-1])
                Av_Point_away.append(float(Point_away[k])/Away)
            
            #Point draw
            if ALL_TEAM[team_index].df['FTR'][i]=='D':
                Point_away.append(1+Point_away[k-1])
                Av_Point_away.append(float(Point_away[k])/Away)
                
            #Point lost
            if ALL_TEAM[team_index].df['FTR'][i]=='H':
                Point_away.append(0+Point_away[k-1])
                Av_Point_away.append(float(Point_away[k])/Away)
            
            Point_home.append(Point_home[k-1])
            Av_Point_home.append(Av_Point_home[k-1])
        
            
            
        k=k+1
     
 
    del Goal_scored_home[-1]
    del Goal_received_home[-1]
    del Goal_scored_away[-1]
    del Goal_received_away[-1]
    
    
    del Av_Goal_scored_home[-1]
    del Av_Goal_received_home[-1]
    del Av_Goal_scored_away[-1]
    del Av_Goal_received_away[-1]
    
    del Point_home[-1]
    del Point_away[-1]
    del Av_Point_home[-1]
    del Av_Point_away[-1]
    
    
    ALL_TEAM[team_index].df['GS_H']=Goal_scored_home
    ALL_TEAM[team_index].df['GS_A']=Goal_scored_away
    ALL_TEAM[team_index].df['GR_H']=Goal_received_home
    ALL_TEAM[team_index].df['GR_A']=Goal_received_away
    
    
    ALL_TEAM[team_index].df['AGS_H']=Av_Goal_scored_home
    ALL_TEAM[team_index].df['AGS_A']=Av_Goal_scored_away
    ALL_TEAM[team_index].df['AGR_H']=Av_Goal_received_home
    ALL_TEAM[team_index].df['AGR_A']=Av_Goal_received_away
    
    
    ALL_TEAM[team_index].df['Pnt_H']=Point_home
    ALL_TEAM[team_index].df['Pnt_A']=Point_away
    ALL_TEAM[team_index].df['Av_Pnt_H']=Av_Point_home
    ALL_TEAM[team_index].df['Av_pnt_A']=Av_Point_away
    
    return ALL_TEAM[team_index].df

In [67]:
for i in range(len(teams)):
    allteamsresults[i].df=calculate_for_team_i(allteamsresults,teams,i)

/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:146: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:147: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:148: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:149: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:152: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:154: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:155: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:158: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:159: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:160: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:161: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [68]:
allteamsresults[0].df.head(n=3)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,GR_H,GR_A,AGS_H,AGS_A,AGR_H,AGR_A,Pnt_H,Pnt_A,Av_Pnt_H,Av_pnt_A
0,13/08/16,Burnley,Swansea,0,1,A,0,0,D,J Moss,...,0,0,0.0,0.0,0.0,0.0,0,0,0.0,0.0
11,20/08/16,Burnley,Liverpool,2,0,H,2,0,H,L Mason,...,1,0,0.0,0.0,1.0,0.0,0,0,0.0,0.0
20,27/08/16,Chelsea,Burnley,3,0,H,2,0,H,M Clattenburg,...,1,0,1.0,0.0,0.5,0.0,3,0,1.5,0.0

In [69]:
try_=season.head(n=18)

In [94]:
try_

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee
0,13/08/16,Burnley,Swansea,0,1,A,0,0,D,J Moss
1,13/08/16,Crystal Palace,West Brom,0,1,A,0,0,D,C Pawson
2,13/08/16,Everton,Tottenham,1,1,D,1,0,H,M Atkinson
3,13/08/16,Hull,Leicester,2,1,H,1,0,H,M Dean
4,13/08/16,Man City,Sunderland,2,1,H,1,0,H,R Madley
5,13/08/16,Middlesbrough,Stoke,1,1,D,1,0,H,K Friend
6,13/08/16,Southampton,Watford,1,1,D,0,1,A,R East
7,14/08/16,Arsenal,Liverpool,3,4,A,1,1,D,M Oliver
8,14/08/16,Bournemouth,Man United,1,3,A,0,1,A,A Marriner
9,15/08/16,Chelsea,West Ham,2,1,H,0,0,D,A Taylor
10,19/08/16,Man United,Southampton,2,0,H,1,0,H,A Taylor
11,20/08/16,Burnley,Liverpool,2,0,H,2,0,H,L Mason
12,20/08/16,Leicester,Arsenal,0,0,D,0,0,D,M Clattenburg
13,20/08/16,Stoke,Man City,1,4,A,0,2,A,M Dean
14,20/08/16,Swansea,Hull,0,2,A,0,0,D,S Attwell
15,20/08/16,Tottenham,Crystal Palace,1,0,H,0,0,D,M Oliver
16,20/08/16,Watford,Chelsea,1,2,A,0,0,D,J Moss
17,20/08/16,West Brom,Everton,1,2,A,1,1,D,N Swarbrick

In [165]:
season

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee
0,13/08/16,Burnley,Swansea,0,1,A,0,0,D,J Moss
1,13/08/16,Crystal Palace,West Brom,0,1,A,0,0,D,C Pawson
2,13/08/16,Everton,Tottenham,1,1,D,1,0,H,M Atkinson
3,13/08/16,Hull,Leicester,2,1,H,1,0,H,M Dean
4,13/08/16,Man City,Sunderland,2,1,H,1,0,H,R Madley
5,13/08/16,Middlesbrough,Stoke,1,1,D,1,0,H,K Friend
6,13/08/16,Southampton,Watford,1,1,D,0,1,A,R East
7,14/08/16,Arsenal,Liverpool,3,4,A,1,1,D,M Oliver
8,14/08/16,Bournemouth,Man United,1,3,A,0,1,A,A Marriner
9,15/08/16,Chelsea,West Ham,2,1,H,0,0,D,A Taylor
10,19/08/16,Man United,Southampton,2,0,H,1,0,H,A Taylor
11,20/08/16,Burnley,Liverpool,2,0,H,2,0,H,L Mason
12,20/08/16,Leicester,Arsenal,0,0,D,0,0,D,M Clattenburg
13,20/08/16,Stoke,Man City,1,4,A,0,2,A,M Dean
14,20/08/16,Swansea,Hull,0,2,A,0,0,D,S Attwell
15,20/08/16,Tottenham,Crystal Palace,1,0,H,0,0,D,M Oliver
16,20/08/16,Watford,Chelsea,1,2,A,0,0,D,J Moss
17,20/08/16,West Brom,Everton,1,2,A,1,1,D,N Swarbrick
18,21/08/16,Sunderland,Middlesbrough,1,2,A,0,2,A,M Atkinson
19,21/08/16,West Ham,Bournemouth,1,0,H,0,0,D,C Pawson
20,27/08/16,Chelsea,Burnley,3,0,H,2,0,H,M Clattenburg
21,27/08/16,Crystal Palace,Bournemouth,1,1,D,0,1,A,M Dean
22,27/08/16,Everton,Stoke,1,0,H,0,0,D,M Oliver
23,27/08/16,Hull,Man United,0,1,A,0,0,D,J Moss
24,27/08/16,Leicester,Swansea,2,1,H,1,0,H,R East
25,27/08/16,Southampton,Sunderland,1,1,D,0,0,D,L Mason
26,27/08/16,Tottenham,Liverpool,1,1,D,0,1,A,R Madley
27,27/08/16,Watford,Arsenal,1,3,A,0,3,A,K Friend
28,28/08/16,Man City,West Ham,3,1,H,2,0,H,A Marriner
29,28/08/16,West Brom,Middlesbrough,0,0,D,0,0,D,A Taylor
...,...,...,...,...,...,...,...,...,...,...
253,25/02/17,Hull,Burnley,1,1,D,0,0,D,M Atkinson
254,25/02/17,Watford,West Ham,1,1,D,1,0,H,C Pawson
255,25/02/17,West Brom,Bournemouth,2,1,H,2,1,H,M Clattenburg
256,26/02/17,Tottenham,Stoke,4,0,H,4,0,H,J Moss
257,27/02/17,Leicester,Liverpool,3,1,H,2,0,H,M Oliver
258,04/03/17,Leicester,Hull,3,1,H,1,1,D,M Dean
259,04/03/17,Liverpool,Arsenal,3,1,H,2,0,H,R Madley
260,04/03/17,Man United,Bournemouth,1,1,D,1,1,D,K Friend
261,04/03/17,Stoke,Middlesbrough,2,0,H,2,0,H,C Pawson
262,04/03/17,Swansea,Burnley,3,2,H,1,1,D,A Taylor
263,04/03/17,Watford,Southampton,3,4,A,1,2,A,J Moss
264,04/03/17,West Brom,Crystal Palace,0,2,A,0,0,D,M Jones
265,05/03/17,Sunderland,Man City,0,2,A,0,1,A,M Atkinson
266,05/03/17,Tottenham,Everton,3,2,H,1,0,H,M Oliver
267,06/03/17,West Ham,Chelsea,1,2,A,0,1,A,A Marriner
268,08/03/17,Man City,Stoke,0,0,D,0,0,D,N Swarbrick
269,11/03/17,Bournemouth,West Ham,3,2,H,1,1,D,R Madley
270,11/03/17,Everton,West Brom,3,0,H,2,0,H,G Scott
271,11/03/17,Hull,Swansea,2,1,H,0,0,D,A Marriner
272,12/03/17,Liverpool,Burnley,2,1,H,1,1,D,C Pawson
273,18/03/17,Bournemouth,Swansea,2,0,H,1,0,H,M Dean
274,18/03/17,Crystal Palace,Watford,1,0,H,0,0,D,M Atkinson
275,18/03/17,Everton,Hull,4,0,H,1,0,H,P Tierney
276,18/03/17,Stoke,Chelsea,1,2,A,1,1,D,A Taylor
277,18/03/17,Sunderland,Burnley,0,0,D,0,0,D,R Madley
278,18/03/17,West Brom,Arsenal,3,1,H,1,1,D,N Swarbrick
279,18/03/17,West Ham,Leicester,2,3,A,1,3,A,R East
280,19/03/17,Man City,Liverpool,1,1,D,0,0,D,M Oliver
281,19/03/17,Middlesbrough,Man United,1,3,A,0,1,A,J Moss
282,19/03/17,Tottenham,Southampton,2,1,H,2,0,H,A Marriner

In [181]:
tmp=pd.DataFrame(columns=('H_GS_H', 'H_GS_A', 'H_GR_H', 'H_GR_A', 'H_AGS_H' ,'H_AGS_A' ,'H_AGR_H','H_AGR_A','H_Pnt_H' ,'H_Pnt_A','H_Av_Pnt_H','H_Av_pnt_A','Aw_GS_H', 'Aw_GS_A', 'Aw_GR_H', 'Aw_GR_A', 'Aw_AGS_H' ,'Aw_AGS_A' ,'Aw_AGR_H','Aw_AGR_A','Aw_Pnt_H' ,'Aw_Pnt_A','Aw_Av_Pnt_H','Aw_Av_pnt_A'))

for i in season.index:
    
    date=season['Date'][i]
    Home=season['HomeTeam'][i]
    Away=season['AwayTeam'][i]
    
    home_index=pd.Series(teams)[teams==Home].index[0]
    away_index=pd.Series(teams)[teams==Away].index[0]
    tobeappend=list(allteamsresults[home_index].df.loc[i].iloc[10:]) + list(allteamsresults[away_index].df.loc[i].iloc[10:])
    tmp.loc[i]=tobeappend

In [182]:
final=pd.merge(left=season, right=tmp, left_index=True, right_index=True)

In [205]:
mean=allteamsresults[0].df[allteamsresults[0].df['HomeTeam']=='Burnley'].iloc[:8]['FTHG'].mean()
std=allteamsresults[0].df[allteamsresults[0].df['HomeTeam']=='Burnley'].iloc[:8]['FTHG'].std()

In [211]:
allteamsresults[0].df[allteamsresults[0].df['HomeTeam']=='Burnley'].iloc[:9]['FTHG']

0      0
11     2
32     1
59     2
66     0
82     2
101    3
120    1
141    3
Name: FTHG, dtype: int64

In [206]:
import numpy.random as np
import random

In [207]:
random.choice(np.normal(mean,std,size=100))

1.1783564247242757

In [208]:
lis=[]

for i in range(10000):
    lis.append(abs(random.choice(np.normal(mean,std,size=100))))

In [210]:
float(sum(lis))/len(lis)

1.4671868568228745