In [506]:
import pandas as pd
pd.options.display.max_columns = 999
pd.options.display.max_rows = 30

In [507]:
##Define the object for the season team
class MyDf:
    def __init__(self, mydf):
        self.df = mydf

# Creating the teams dataframe

In [508]:
TEAMNAMES=pd.read_csv('../Data/from_sqlite_Data/Team.csv')
LEAGUENAMES= pd.read_csv('../Data/from_sqlite_Data/League.csv')
df2 = pd.read_csv('../Data/from_sqlite_Data/bigfinal.csv')
df2.drop(['Unnamed: 0'],axis=1,inplace=True)
df2.drop(['league_id'],axis=1,inplace=True)
df2.drop(['id'],axis=1,inplace=True)

In [509]:
season = df2
FTR=[]
for i in range(len(season)):
    if season['FTHG'][i]>season['FTAG'][i]:
        FTR.append('H')
    if season['FTHG'][i]<season['FTAG'][i]:
        FTR.append('A')
    if season['FTHG'][i]==season['FTAG'][i]:
        FTR.append('D')
    
season['FTR']=FTR

In [510]:
season=season.sort('Date')

/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [511]:
season.reset_index(inplace=True)

In [512]:
season.drop(['index'],axis=1,inplace=True)

In [513]:
#season['season']=['2016/2017']*len(season)

In [514]:
teams=season.HomeTeam.unique()
allteamsresults=[]
for i in teams:
    path=pd.DataFrame()            
    path = season[(season["HomeTeam"] == i) | (season['AwayTeam'] == i )] 
    allteamsresults.append(MyDf(path))

In [344]:
def point_in_round_k(ALL_TEAM,i,team_index,where):
    
    home=where
    away= not home
    
    if home:
        if ALL_TEAM[team_index].df['FTR'][i]=='H':
            return 3
        if ALL_TEAM[team_index].df['FTR'][i]=='D':
            return 1
        if ALL_TEAM[team_index].df['FTR'][i]=='A':
            return 0
    #   
    if away:
        if ALL_TEAM[team_index].df['FTR'][i]=='H':
            return 0
        if ALL_TEAM[team_index].df['FTR'][i]=='D':
            return 1
        if ALL_TEAM[team_index].df['FTR'][i]=='A':
            return 3

In [345]:
def zero_or_big(a,b):
    if a-b>0:
        return a-b
    return 0

In [346]:
def poin_in_last_n_mathces(ALL_TEAM,i,team_index,where,round_index,n):
    if round_index<=n:
        return point_in_round_k(ALL_TEAM,i,team_index,where)

## Allteamsresults is a list of dataframes and each dataframe represents a specific team. To access info on a team use team index. The position of the team in the list "teams" gives  the index of the team in the "allteamsresults" list of dataframes.

## Now, lets calculate some other features

## 1) Goal scored and received - home and away.
### We will shift of one match back each calculation, which means, each row will have the present match and the statistics goals scored up to that day (before the match).

In [379]:
def calculate_for_team_i(ALL_TEAM,team_lists,team_index):
    
    #create the lists for goals 
    Goal_scored_home=[]
    Goal_received_home=[]
    Goal_scored_away=[]
    Goal_received_away=[]
    
    #total_goal
    total_goal_scored=[]
    total_goal_received=[]
    
    #create the list for averages goals
    Av_Goal_scored_home=[]
    Av_Goal_received_home=[]
   

    Av_Goal_scored_away=[]
    Av_Goal_received_away=[]
       
    #create the list for averages total goals
    Av_total_goal_scored=[]
    Av_total_goal_received=[]
    
    #create the lists for points
    Point_home=[]
    Point_away=[]

    total_point=[]

    #create the list for average Points
    Av_Point_home=[]
    Av_Point_away=[]

    Av_total_point=[]
    
    
    #Point in the last mathces
    
    T_L3M_Pnt=[]
    T_L5M_Pnt=[]
    
    H_L3M_Pnt=[]
    A_L3M_Pnt=[]
    
    H_L5M_Pnt=[]
    A_L5M_Pnt=[]
    
    
    
    #ROUND_INDEX
    round_index=[]

    
    k=1
    
    Goal_scored_home.append(0)
    Goal_received_home.append(0)
    Goal_scored_away.append(0)
    Goal_received_away.append(0)
    total_goal_scored.append(0)
    total_goal_received.append(0)
    Av_Goal_scored_home.append(0)
    Av_Goal_received_home.append(0)
    Av_Goal_scored_away.append(0)
    Av_Goal_received_away.append(0)
    Av_total_goal_scored.append(0)
    Av_total_goal_received.append(0)
    Point_home.append(0)
    Point_away.append(0)
    total_point.append(0)
    Av_Point_home.append(0)
    Av_Point_away.append(0)
    Av_total_point.append(0) 
    T_L3M_Pnt.append(0)
    T_L5M_Pnt.append(0)
    #H_L3M_Pnt.append(0)
    #A_L3M_Pnt.append(0)
    #H_L5M_Pnt.append(0)
    #A_L5M_Pnt.append(0)
    
    
    for h in allteamsresults[team_index].df['season'].unique():
    
        seasonal_index=allteamsresults[team_index].df[allteamsresults[team_index].df['season']==h].index
        Home=0
        Away=0
        total=0
        round_in=1
        tmp3=[]
        tmp5=[]
        
        for i in seasonal_index:
            
            round_index.append(round_in)
            round_index_2=round_in-1
            
            home_1=ALL_TEAM[team_index].df['HomeTeam'][i]==team_lists[team_index]
            away_1= not home_1
            

            if (round_in<=3):
                if home_1:
                    if ALL_TEAM[team_index].df['FTR'][i]=='H':
                        T_L3M_Pnt.append(3)
                        tmp3.append(3)
                        #H_L3M_Pnt.append(3)
                        #A_L3M_Pnt.append(A_L3M_Pnt[k-1])
                    if ALL_TEAM[team_index].df['FTR'][i]=='D':
                        T_L3M_Pnt.append(1) 
                        tmp3.append(1)                        
                        #H_L3M_Pnt.append(1)
                        #A_L3M_Pnt.append(A_L3M_Pnt[k-1])
                    if ALL_TEAM[team_index].df['FTR'][i]=='A':
                        T_L3M_Pnt.append(0)                        
                        tmp3.append(0)
                        #H_L3M_Pnt.append(0)
                        #A_L3M_Pnt.append(A_L3M_Pnt[k-1])
                #   
                if away_1:
                    if ALL_TEAM[team_index].df['FTR'][i]=='H':
                        T_L3M_Pnt.append(0)
                        tmp3.append(0)
                        #H_L3M_Pnt.append(H_L3M_Pnt[k-1])
                        #A_L3M_Pnt.append(0)
                    if ALL_TEAM[team_index].df['FTR'][i]=='D':
                        T_L3M_Pnt.append(1)
                        tmp3.append(1)
                        #H_L3M_Pnt.append(H_L3M_Pnt[k-1])
                        #A_L3M_Pnt.append(1)
                    if ALL_TEAM[team_index].df['FTR'][i]=='A':
                        T_L3M_Pnt.append(3)
                        tmp3.append(3)
                        #H_L3M_Pnt.append(H_L3M_Pnt[k-1])
                        #A_L3M_Pnt.append(3)
            #                        
            if (round_in<=5):
                if home_1:
                    if ALL_TEAM[team_index].df['FTR'][i]=='H':
                        T_L5M_Pnt.append(3)
                        tmp5.append(3)
                        #H_L5M_Pnt.append(3)
                        #A_L5M_Pnt.append(A_L5M_Pnt[k-1])

                    if ALL_TEAM[team_index].df['FTR'][i]=='D':
                        T_L5M_Pnt.append(1)
                        tmp5.append(1)
                        #H_L5M_Pnt.append(1)
                        #A_L5M_Pnt.append(A_L5M_Pnt[k-1])

                    if ALL_TEAM[team_index].df['FTR'][i]=='A':
                        T_L5M_Pnt.append(0)
                        tmp5.append(0)
                        #H_L5M_Pnt.append(0)
                        #A_L5M_Pnt.append(A_L5M_Pnt[k-1])

                if away_1:
                    if ALL_TEAM[team_index].df['FTR'][i]=='H':
                        T_L5M_Pnt.append(0)
                        tmp5.append(0)
                        #H_L5M_Pnt.append(H_L5M_Pnt[k-1])
                        #A_L5M_Pnt.append(0)

                    if ALL_TEAM[team_index].df['FTR'][i]=='D':
                        T_L5M_Pnt.append(1)
                        tmp5.append(1)
                        #H_L5M_Pnt.append(H_L5M_Pnt[k-1])
                        #A_L5M_Pnt.append(1)

                    if ALL_TEAM[team_index].df['FTR'][i]=='A':
                        T_L5M_Pnt.append(3)
                        tmp5.append(3)
                        #H_L5M_Pnt.append(H_L5M_Pnt[k-1])
                        #A_L5M_Pnt.append(3)
                        
            '''if (round_in==3):
                if home_1:
                    if ALL_TEAM[team_index].df['FTR'][i]=='H':
                        T_L3M_Pnt.append(3++T_L3M_Pnt[round_index_2-1]+T_L3M_Pnt[round_index_2-2])
                        #H_L3M_Pnt.append(3)
                        #A_L3M_Pnt.append(A_L3M_Pnt[k-1])
                    if ALL_TEAM[team_index].df['FTR'][i]=='D':
                        T_L3M_Pnt.append(1++T_L3M_Pnt[round_index_2-1]+T_L3M_Pnt[round_index_2-2])                        
                        #H_L3M_Pnt.append(1)
                        #A_L3M_Pnt.append(A_L3M_Pnt[k-1])
                    if ALL_TEAM[team_index].df['FTR'][i]=='A':
                        T_L3M_Pnt.append(0++T_L3M_Pnt[round_index_2-1]+T_L3M_Pnt[round_index_2-2])                        
                        #H_L3M_Pnt.append(0)
                        #A_L3M_Pnt.append(A_L3M_Pnt[k-1])
                #   
                #
                if away_1:
                    if ALL_TEAM[team_index].df['FTR'][i]=='H':
                        T_L3M_Pnt.append(0++T_L3M_Pnt[round_index_2-1]+T_L3M_Pnt[round_index_2-2])
                        #H_L3M_Pnt.append(H_L3M_Pnt[k-1])
                        #A_L3M_Pnt.append(0)
                    if ALL_TEAM[team_index].df['FTR'][i]=='D':
                        T_L3M_Pnt.append(1+T_L3M_Pnt[round_index_2-1]+T_L3M_Pnt[round_index_2-2])
                        #H_L3M_Pnt.append(H_L3M_Pnt[k-1])
                        #A_L3M_Pnt.append(1)
                    if ALL_TEAM[team_index].df['FTR'][i]=='A':
                        T_L3M_Pnt.append(3++T_L3M_Pnt[round_index_2-1]+T_L3M_Pnt[round_index_2-2])
                        #H_L3M_Pnt.append(H_L3M_Pnt[k-1])
                        #A_L3M_Pnt.append(3)
            
            if (round_in==5):
                if home_1:
                    if ALL_TEAM[team_index].df['FTR'][i]=='H':
                        T_L5M_Pnt.append(3+T_L5M_Pnt[round_index_2-1]+T_L5M_Pnt[round_index_2-2]+T_L5M_Pnt[round_index_2-3]
                                        +T_L5M_Pnt[round_index_2-4])
                        #H_L5M_Pnt.append(3)
                        #A_L5M_Pnt.append(A_L5M_Pnt[k-1])

                    if ALL_TEAM[team_index].df['FTR'][i]=='D':
                        T_L5M_Pnt.append(1+T_L5M_Pnt[round_index_2-1]+T_L5M_Pnt[round_index_2-2]+T_L5M_Pnt[round_index_2-3]
                                        +T_L5M_Pnt[round_index_2-4])
                        #H_L5M_Pnt.append(1)
                        #A_L5M_Pnt.append(A_L5M_Pnt[k-1])

                    if ALL_TEAM[team_index].df['FTR'][i]=='A':
                        T_L5M_Pnt.append(0+T_L5M_Pnt[round_index_2-1]+T_L5M_Pnt[round_index_2-2]+T_L5M_Pnt[round_index_2-3]
                                        +T_L5M_Pnt[round_index_2-4])
                        #H_L5M_Pnt.append(0)
                        #A_L5M_Pnt.append(A_L5M_Pnt[k-1])
                if away_1:
                    if ALL_TEAM[team_index].df['FTR'][i]=='H':
                        T_L5M_Pnt.append(0+T_L5M_Pnt[round_index_2-1]+T_L5M_Pnt[round_index_2-2]+T_L5M_Pnt[round_index_2-3]
                                        +T_L5M_Pnt[round_index_2-4])
                        #H_L5M_Pnt.append(H_L5M_Pnt[k-1])
                        #A_L5M_Pnt.append(0)

                    if ALL_TEAM[team_index].df['FTR'][i]=='D':
                        T_L5M_Pnt.append(1+T_L5M_Pnt[round_index_2-1]+T_L5M_Pnt[round_index_2-2]+T_L5M_Pnt[round_index_2-3]
                                        +T_L5M_Pnt[round_index_2-4])
                        #H_L5M_Pnt.append(H_L5M_Pnt[k-1])
                        #A_L5M_Pnt.append(1)

                    if ALL_TEAM[team_index].df['FTR'][i]=='A':
                        T_L5M_Pnt.append(3+T_L5M_Pnt[round_index_2-1]+T_L5M_Pnt[round_index_2-2]+T_L5M_Pnt[round_index_2-3]
                                        +T_L5M_Pnt[round_index_2-4])
                        #H_L5M_Pnt.append(H_L5M_Pnt[k-1])
                        #A_L5M_Pnt.append(3)
'''
            if (round_in>3):
                if home_1:
                    if ALL_TEAM[team_index].df['FTR'][i]=='H':
                        tmp3.append(3)
                        del tmp3[0]
                        T_L3M_Pnt.append(sum(tmp3))

                    if ALL_TEAM[team_index].df['FTR'][i]=='D':  
                        tmp3.append(1)
                        del tmp3[0]
                        T_L3M_Pnt.append(sum(tmp3))
                    
                    if ALL_TEAM[team_index].df['FTR'][i]=='A':
                        tmp3.append(0)
                        del tmp3[0]
                        T_L3M_Pnt.append(sum(tmp3))
                        
                if away_1:
                    if ALL_TEAM[team_index].df['FTR'][i]=='H':
                        tmp3.append(0)
                        del tmp3[0]
                        T_L3M_Pnt.append(sum(tmp3))
                        
                    if ALL_TEAM[team_index].df['FTR'][i]=='D':  
                        tmp3.append(1)
                        del tmp3[0]
                        T_L3M_Pnt.append(sum(tmp3))
                        
                        
                    if ALL_TEAM[team_index].df['FTR'][i]=='A':
                        tmp3.append(3)
                        del tmp3[0]
                        T_L3M_Pnt.append(sum(tmp3))
                        
                        
            if (round_in>5):
                if home_1:
                    if ALL_TEAM[team_index].df['FTR'][i]=='H':
                        tmp5.append(3)
                        del tmp5[0]
                        T_L5M_Pnt.append(sum(tmp5))
                        
                    if ALL_TEAM[team_index].df['FTR'][i]=='D':
                        tmp5.append(1)
                        del tmp5[0]
                        T_L5M_Pnt.append(sum(tmp5))
                        
                    if ALL_TEAM[team_index].df['FTR'][i]=='A':
                        tmp5.append(0)
                        del tmp5[0]
                        T_L5M_Pnt.append(sum(tmp5))
                        
                if away_1:
                    if ALL_TEAM[team_index].df['FTR'][i]=='H':
                        tmp5.append(0)
                        del tmp5[0]
                        T_L5M_Pnt.append(sum(tmp5))
                        
                    if ALL_TEAM[team_index].df['FTR'][i]=='D':
                        tmp5.append(1)
                        del tmp5[0]
                        T_L5M_Pnt.append(sum(tmp5))
                        
                    if ALL_TEAM[team_index].df['FTR'][i]=='A':
                        tmp5.append(3)
                        del tmp5[0]
                        T_L5M_Pnt.append(sum(tmp5))
            
            round_in=round_in+1
            

            #HOME
            if ALL_TEAM[team_index].df['HomeTeam'][i]==team_lists[team_index]:

                #Goal scored, received and total
                Goal_scored_home.append(ALL_TEAM[team_index].df['FTHG'][i]+Goal_scored_home[k-1])
                Goal_received_home.append(ALL_TEAM[team_index].df['FTAG'][i]+Goal_received_home[k-1])  
                Goal_scored_away.append(Goal_scored_away[k-1])
                Goal_received_away.append(Goal_received_away[k-1])
                total_goal_scored.append(total_goal_scored[k-1]+ALL_TEAM[team_index].df['FTHG'][i])
                total_goal_received.append(total_goal_received[k-1]+ALL_TEAM[team_index].df['FTAG'][i])

                #Goal average
                Home=Home+1
                total=Home+Away
                Av_Goal_scored_home.append(float(Goal_scored_home[k])/Home)
                Av_Goal_received_home.append(float(Goal_received_home[k])/Home)
                Av_Goal_scored_away.append(Av_Goal_scored_away[k-1])
                Av_Goal_received_away.append(Av_Goal_received_away[k-1])
                Av_total_goal_scored.append(float(total_goal_scored[k])/total)
                Av_total_goal_received.append(float(total_goal_received[k])/total)


                #Point winning
                if ALL_TEAM[team_index].df['FTR'][i]=='H':
                    Point_home.append(3+Point_home[k-1])
                    Av_Point_home.append(float(Point_home[k])/Home)
                    total_point.append(3+total_point[k-1])
                    Av_total_point.append(float(total_point[k])/total)

                #Point draw
                if ALL_TEAM[team_index].df['FTR'][i]=='D':
                    Point_home.append(1+Point_home[k-1])
                    Av_Point_home.append(float(Point_home[k])/Home)
                    total_point.append(1+total_point[k-1])
                    Av_total_point.append(float(total_point[k])/total)

                #Point lost
                if ALL_TEAM[team_index].df['FTR'][i]=='A':
                    Point_home.append(0+Point_home[k-1])
                    Av_Point_home.append(float(Point_home[k])/Home)   
                    total_point.append(0+total_point[k-1])
                    Av_total_point.append(float(total_point[k])/total)

                Point_away.append(Point_away[k-1])
                Av_Point_away.append(Av_Point_away[k-1])

            #AWAY
            if ALL_TEAM[team_index].df['HomeTeam'][i]!=team_lists[team_index]:

                #Goal scored, received and total
                Goal_scored_away.append(ALL_TEAM[team_index].df['FTAG'][i]+Goal_scored_away[k-1])
                Goal_received_away.append(ALL_TEAM[team_index].df['FTHG'][i]+Goal_received_away[k-1])
                Goal_scored_home.append(Goal_scored_home[k-1])
                Goal_received_home.append(Goal_received_home[k-1])
                total_goal_scored.append(total_goal_scored[k-1]+ALL_TEAM[team_index].df['FTAG'][i])
                total_goal_received.append(total_goal_received[k-1]+ALL_TEAM[team_index].df['FTHG'][i])

                #Goal average
                Away=Away+1
                total=Home+Away

                Av_Goal_scored_away.append(float(Goal_scored_away[k])/Away)
                Av_Goal_received_away.append(float(Goal_received_away[k])/Away)
                Av_Goal_scored_home.append(Av_Goal_scored_home[k-1])
                Av_Goal_received_home.append(Av_Goal_received_home[k-1])
                Av_total_goal_scored.append(float(total_goal_scored[k])/total)
                Av_total_goal_received.append(float(total_goal_received[k])/total)


                #Point winning
                if ALL_TEAM[team_index].df['FTR'][i]=='A':
                    Point_away.append(3+Point_away[k-1])
                    Av_Point_away.append(float(Point_away[k])/Away)
                    total_point.append(3+total_point[k-1])
                    Av_total_point.append(float(total_point[k])/total)

                #Point draw
                if ALL_TEAM[team_index].df['FTR'][i]=='D':
                    Point_away.append(1+Point_away[k-1])
                    Av_Point_away.append(float(Point_away[k])/Away)

                    total_point.append(1+total_point[k-1])
                    Av_total_point.append(float(total_point[k])/total)

                #Point lost
                if ALL_TEAM[team_index].df['FTR'][i]=='H':
                    Point_away.append(0+Point_away[k-1])
                    Av_Point_away.append(float(Point_away[k])/Away)

                    total_point.append(0+total_point[k-1])
                    Av_total_point.append(float(total_point[k])/total)


                Point_home.append(Point_home[k-1])
                Av_Point_home.append(Av_Point_home[k-1])
                
                


            k=k+1

        
        Goal_scored_home[-1]=0
        Goal_received_home[-1]=0
        Goal_scored_away[-1]=0
        Goal_received_away[-1]=0
        total_goal_scored[-1]=0
        total_goal_received[-1]=0


        Av_Goal_scored_home[-1]=0
        Av_Goal_received_home[-1]=0
        Av_Goal_scored_away[-1]=0
        Av_Goal_received_away[-1]=0
        Av_total_goal_scored[-1]=0
        Av_total_goal_received[-1]=0


        Point_home[-1]=0
        Point_away[-1]=0
        Av_Point_home[-1]=0
        Av_Point_away[-1]=0

        total_point[-1]=0
        Av_total_point[-1]=0
        
        
        T_L3M_Pnt[-1]=0
        T_L5M_Pnt[-1]=0
        

    del Goal_scored_home[-1]
    del Goal_received_home[-1]
    del Goal_scored_away[-1]
    del Goal_received_away[-1]
    del total_goal_scored[-1]
    del total_goal_received[-1]


    del Av_Goal_scored_home[-1]
    del Av_Goal_received_home[-1]
    del Av_Goal_scored_away[-1]
    del Av_Goal_received_away[-1]
    del Av_total_goal_scored[-1]
    del Av_total_goal_received[-1]


    del Point_home[-1]
    del Point_away[-1]
    del Av_Point_home[-1]
    del Av_Point_away[-1]

    del total_point[-1]
    del Av_total_point[-1]
    
    del T_L3M_Pnt[-1]
    del T_L5M_Pnt[-1]
    
    ALL_TEAM[team_index].df['Round']=round_index
    
    ALL_TEAM[team_index].df['T_L3M']=T_L3M_Pnt
    ALL_TEAM[team_index].df['T_L5M']=T_L5M_Pnt
    
    ALL_TEAM[team_index].df['GS_H']=Goal_scored_home
    ALL_TEAM[team_index].df['GS_A']=Goal_scored_away
    ALL_TEAM[team_index].df['GR_H']=Goal_received_home
    ALL_TEAM[team_index].df['GR_A']=Goal_received_away
    ALL_TEAM[team_index].df['TGS']=total_goal_scored
    ALL_TEAM[team_index].df['TGR']=total_goal_received
    
    
    ALL_TEAM[team_index].df['AGS_H']=Av_Goal_scored_home
    ALL_TEAM[team_index].df['AGS_A']=Av_Goal_scored_away
    ALL_TEAM[team_index].df['AGR_H']=Av_Goal_received_home
    ALL_TEAM[team_index].df['AGR_A']=Av_Goal_received_away
    ALL_TEAM[team_index].df['ATGS']=Av_total_goal_scored
    ALL_TEAM[team_index].df['ATGR']=Av_total_goal_received

    
    ALL_TEAM[team_index].df['Pnt_H']=Point_home
    ALL_TEAM[team_index].df['Pnt_A']=Point_away
    ALL_TEAM[team_index].df['TOTPT']=total_point

    
    ALL_TEAM[team_index].df['Av_Pnt_H']=Av_Point_home
    ALL_TEAM[team_index].df['Av_pnt_A']=Av_Point_away
    ALL_TEAM[team_index].df['Av_tot_pnt']=Av_total_point
    
    
    return ALL_TEAM[team_index].df

In [348]:
#calculate_for_team_i(allteamsresults,teams,40)

In [349]:
for i in range(len(teams)):
    allteamsresults[i].df=calculate_for_team_i(allteamsresults,teams,i)

/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:473: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:475: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:476: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:478: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:479: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:480: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:481: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:482: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:483: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:486: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:487: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:488: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:490: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:491: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:495: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:496: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:499: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:500: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:501: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [355]:
allteamsresults[0].df.iloc[:,37:]

,FTR,Round,T_L3M,T_L5M,GS_H,GS_A,GR_H,GR_A,TGS,TGR,AGS_H,AGS_A,AGR_H,AGR_A,ATGS,ATGR,Pnt_H,Pnt_A,TOTPT,Av_Pnt_H,Av_pnt_A,Av_tot_pnt
0,A,1,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0.000000,0.000000,0.000000
7,H,2,0,0,1,0,2,0,1,2,1.000000,0.000000,2.000000,0.000000,1.000000,2.000000,0,0,0,0.000000,0.000000,0.000000
12,D,3,0,0,1,1,2,2,2,4,1.000000,1.000000,2.000000,2.000000,1.000000,2.000000,0,0,0,0.000000,0.000000,0.000000
17,H,4,1,1,1,1,2,2,2,4,0.500000,1.000000,1.000000,2.000000,0.666667,1.333333,1,0,1,0.500000,0.000000,0.333333
46,H,5,1,0,1,2,2,4,3,6,0.500000,1.000000,1.000000,2.000000,0.750000,1.500000,1,0,1,0.500000,0.000000,0.250000
92,A,6,4,3,3,2,3,4,5,7,1.000000,1.000000,1.000000,2.000000,1.000000,1.400000,4,0,4,1.333333,0.000000,0.800000
161,D,7,6,7,3,5,3,4,8,7,1.000000,1.666667,1.000000,1.333333,1.333333,1.166667,4,3,7,1.333333,1.000000,1.166667
224,A,8,7,8,6,5,6,4,11,10,1.500000,1.666667,1.500000,1.333333,1.571429,1.428571,5,3,8,1.250000,1.000000,1.142857
315,A,9,4,7,7,5,9,4,12,13,1.400000,1.666667,1.800000,1.333333,1.500000,1.625000,5,3,8,1.000000,1.000000,1.000000
475,A,10,4,10,7,7,9,5,14,14,1.400000,1.750000,1.800000,1.250000,1.555556,1.555556,5,6,11,1.000000,1.500000,1.222222
622,H,11,6,10,7,9,9,6,16,15,1.400000,1.800000,1.800000,1.200000,1.600000,1.500000,5,9,14,1.000000,1.800000,1.400000
800,D,12,9,10,12,9,9,6,21,15,2.000000,1.800000,1.500000,1.200000,1.909091,1.363636,8,9,17,1.333333,1.800000,1.545455
959,D,13,7,10,12,9,9,6,21,15,2.000000,1.500000,1.500000,1.000000,1.750000,1.250000,8,10,18,1.333333,1.666667,1.500000
1017,A,14,5,11,14,9,11,6,23,17,2.000000,1.500000,1.571429,1.000000,1.769231,1.307692,9,10,19,1.285714,1.666667,1.461538
1121,H,15,5,11,14,12,11,8,26,19,2.000000,1.714286,1.571429,1.142857,1.857143,1.357143,9,13,22,1.285714,1.857143,1.571429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24992,A,22,5,8,22,12,12,13,34,25,2.000000,1.200000,1.090909,1.300000,1.619048,1.190476,22,11,33,2.000000,1.100000,1.571429
25156,H,23,7,8,22,13,12,13,35,25,2.000000,1.181818,1.090909,1.181818,1.590909,1.136364,22,14,36,2.000000,1.272727,1.636364
25246,H,24,9,11,27,13,14,13,40,27,2.250000,1.181818,1.166667,1.181818,1.739130,1.173913,25,14,39,2.083333,1.272727,1.695652
25311,A,25,9,13,30,13,16,13,43,29,2.307692,1.181818,1.230769,1.181818,1.791667,1.208333,28,14,42,2.153846,1.272727,1.750000
25437,H,26,9,15,30,16,16,15,46,31,2.307692,1.333333,1.230769,1.250000,1.840000,1.240000,28,17,45,2.153846,1.416667,1.800000
25499,H,27,6,12,30,16,16,17,46,33,2.307692,1.230769,1.230769,1.307692,1.769231,1.269231,28,17,45,2.153846,1.307692,1.730769
25597,H,28,6,12,37,16,16,17,53,33,2.642857,1.230769,1.142857,1.307692,1.962963,1.222222,31,17,48,2.214286,1.307692,1.777778
25631,A,29,6,12,42,16,20,17,58,37,2.800000,1.230769,1.333333,1.307692,2.071429,1.321429,34,17,51,2.266667,1.307692,1.821429
25709,H,30,9,12,42,19,20,19,61,39,2.800000,1.357143,1.333333,1.357143,2.103448,1.344828,34,20,54,2.266667,1.428571,1.862069
25765,A,31,9,12,45,19,20,19,64,39,2.812500,1.357143,1.250000,1.357143,2.133333,1.300000,37,20,57,2.312500,1.428571,1.900000
25860,H,32,9,15,45,21,20,20,66,40,2.812500,1.400000,1.250000,1.333333,2.129032,1.290323,37,23,60,2.312500,1.533333,1.935484
25899,H,33,6,12,45,22,20,22,67,42,2.812500,1.375000,1.250000,1.375000,2.093750,1.312500,37,23,60,2.312500,1.437500,1.875000
25964,A,34,6,12,48,22,21,22,70,43,2.823529,1.375000,1.235294,1.375000,2.121212,1.303030,40,23,63,2.352941,1.437500,1.909091
25971,A,35,6,12,48,25,21,23,73,44,2.823529,1.470588,1.235294,1.352941,2.147059,1.294118,40,26,66,2.352941,1.529412,1.941176
25977,A,36,6,9,50,25,24,23,75,47,2.777778,1.470588,1.333333,1.352941,2.142857,1.342857,40,26,66,2.222222,1.529412,1.885714

In [354]:
tmp=pd.DataFrame(columns=(
                          'H_ROUND',
    
                          'H_TP3',
                          'H_TP5',
                            
    
                          'H_GS_H', 
                          'H_GS_A', 
                          'H_GR_H', 
                          'H_GR_A', 
                          'H_TGS',
                          'H_TGR', 
                          
                          'H_AvGS_H' ,
                          'H_AvGS_A' ,
                          'H_AvGR_H',
                          'H_AvGR_A',
                          'H_Av_TGS',
                          'H_Av_TGR', 
                          
                          
                          'H_Pnt_H' ,
                          'H_Pnt_A',
                          'H_T_pnt',
                          'H_Av_Pnt_H',
                          'H_Av_pnt_A',
                          'H_Av_T_pnt',
                          
                          'A_ROUND',
    
                          'A_TP3',
                          'A_TP5',

                          'Aw_GS_H', 
                          'Aw_GS_A', 
                          'Aw_GR_H', 
                          'Aw_GR_A', 
                          'Aw_TGS',
                          'Aw_TGR', 
                          
                          'Aw_AvGS_H' ,
                          'Aw_AvGS_A' ,
                          'Aw_AvGR_H',
                          'Aw_AvGR_A',
                          'Aw_Av_TGS',
                          'Aw_Av_TGR', 
                          
                          
                          'Aw_Pnt_H' ,
                          'Aw_Pnt_A',
                          'Aw_T_pnt',
                          'Aw_Av_Pnt_H',
                          'Aw_Av_pnt_A',
                         
                          'Aw_Av_T_pnt',
                          
                          
                          
                         )
                )

In [ ]:
allteamsresults.[0]df.iloc[37:]

In [356]:
for i in season.index:
    date=season['Date'][i]
    Home=season['HomeTeam'][i]
    Away=season['AwayTeam'][i]
    
    home_index=pd.Series(teams)[teams==Home].index[0]
    away_index=pd.Series(teams)[teams==Away].index[0]
    tobeappend=list(allteamsresults[home_index].df.loc[i].iloc[38:]) + list(allteamsresults[away_index].df.loc[i].iloc[38:])
    tmp.loc[i]=tobeappend

In [357]:
final=pd.merge(left=season, right=tmp, left_index=True, right_index=True)

In [358]:
final['DIFF_TP']=final['H_T_pnt']-final['Aw_T_pnt']
final['DIFF_HP-AP']=final['H_Pnt_H']-final['Aw_Pnt_A']

final['SUMM_HGSH+HGSH+AGRA']=final['H_GS_H']+final['Aw_GR_A']
final['SUMM_HGRH+AGSA']=final['H_GR_H']+final['Aw_GS_A']
final['SUMM_HTGS+ATGR']=final['H_TGS']+final['Aw_TGR']
final['SUMM_HTGR+ATGS']=final['H_TGR']+final['Aw_TGS']

final['DIFF_L3MP']=final['H_TP3']-final['A_TP3']
final['DIFF_L5MP']=final['H_TP5']-final['A_TP5']


final['DIFF_av_TP']=final['H_Av_T_pnt']-final['Aw_Av_T_pnt']
final['DIFF_av_HP-AP']=final['H_Av_Pnt_H']-final['Aw_Av_pnt_A']

final['SUMM_av_HGSH+AGRA']=final['H_AvGS_H']+final['Aw_AvGR_A']
final['SUMM_av_HGRH+AGSA']=final['H_AvGR_H']+final['Aw_AvGS_A']

final['SUMM_av_HTGS+ATGR']=final['H_Av_TGS']+final['Aw_Av_TGR']
final['SUMM_av_HTGR+ATGS']=final['H_Av_TGR']+final['Aw_Av_TGS']

final['Goal/No_Goal'] = ((final['FTHG']>0 ) * 1)*((final['FTAG']>0) * 1)
final['Over2.5/Under2.5'] = ((final['FTHG'] + final['FTAG']) >2)*1
final['Over1.5/Under1.5'] = ((final['FTHG'] + final['FTAG']) >1)*1

In [381]:
final.to_csv('../Data/from_sqlite_Data/Realfinal.csv')

In [515]:
final=pd.read_csv('../Data/from_sqlite_Data/Realfinal.csv')

# ELO

In [360]:
import io
import requests

In [423]:
k=0
for i in final.Date.unique():
    try:
        a=i.replace('00:00:00','')
        a=a.replace(' ','')
        url='http://api.clubelo.com/'+a
        s=requests.get(url).content
        c=pd.read_csv(io.StringIO(s.decode('utf-8')))
        saveto='../Data/elo/'+a
        c.to_csv(saveto)
    except:
        'EmptyDataError: No columns to parse from file'
        k=k+1

In [518]:
concat=[]
k=0
for i in final.Date.unique():    
    a=i.replace('00:00:00','')
    a=a.replace(' ','')
    concat.append(pd.read_csv('../Data/elo/'+a))

In [519]:
all_elo=pd.concat(concat)

In [432]:
all_elo.to_csv('../Data/elo/elo_totale')

# Merging dataframe with elo

In [520]:
import difflib

In [533]:
k=0
a=[]
b=[]
c=[]
r=list(final.HomeTeam.unique())
t=list(all_elo.Club.unique())

for i in r:
    if i in t:
        t.remove(i)
        r.remove(i)

In [536]:
for i in r:
    if i not in t:
        if len(difflib.get_close_matches(i,t))>1:
            a.append(list(difflib.get_close_matches(i,t)))
            b.append(i)
        if len(difflib.get_close_matches(i,t))==0:
            c.append(i)

In [499]:
len(a)
len(b)

45

In [537]:
for i in range(len(a)):
    print a[i]
    print b[i]
    
    
    stokecity--> Stoke
    Sporting Lokeren--->Lokeren
    Estrela Amadora--> Amadora
    Chievo Verona--->Chievo
    Sevilla FC--->

['Aarau', 'Farul']
FC Aarau
['Luzern', 'Lautern']
FC Luzern
['Bellinzona', 'Avellino']
AC Bellinzona
['Basel', 'FC Tiraspol']
FC Basel
['Vaduz', 'Cadiz']
FC Vaduz
['Valenciennes', 'Valencia']
Valenciennes FC
['Wolfsburg', 'Wolfsberg']
VfL Wolfsburg
['St Mirren', 'St Truiden']
St. Mirren
['West Ham', 'Man United']
West Ham United
['Man United', 'Sheffield United']
Manchester United
['Frankfurt', 'FSV Frankfurt']
Eintracht Frankfurt
['Lorient', 'Forest']
FC Lorient
['Cork City', 'Stoke', 'Bristol City']
Stoke City
['Newcastle', 'Man United']
Newcastle United
['Sporting', 'Sporting Fingal']
Sporting CP
['Charleroi', 'Sporting', 'Sporting Fingal']
Sporting Charleroi
['Sporting', 'Sporting Fingal', 'Lokeren']
Sporting Lokeren
['Man City', 'Bangor City']
Manchester City
['Aarau', 'Estrela Amadora', 'Sampdoria']
Amadora
['Benfica', 'Senica']
SL Benfica
['Valencia', 'Valenciennes', 'Valerenga']
Valencia CF
['Volendam', 'FC Kobenhavn']
FC Volendam
['Verona', 'Chievo']
Chievo Verona
['Osasuna', 'CA Bastia']
CA Osasuna
['Heracles', 'Hercules']
Heracles Almelo
['Braga', 'N Burgas', 'Banga']
SC Braga
['Sevilla B', 'Sevilla']
Sevilla FC
['Cercle Brugge', 'Brugge']
Club Brugge KV
['Valladolid', 'Real Madrid', 'Real Madrid B']
Real Valladolid
['Barcelona', 'Barcelona B', 'Charlton']
FC Barcelona
['Real Madrid B', 'Real Madrid']
Real Madrid CF
['Villarreal B', 'Villarreal']
Villarreal CF
['St Truiden', 'Saint-Etienne']
Sint-Truidense VV
['Lens', 'Rennes']
RC Lens
['Birmingham', 'Bangor City']
Birmingham City
['Augsburg', 'Duisburg']
FC Augsburg
['Swansea', 'Man City', 'Bangor City']
Swansea City
['Norwich', 'Cork City', 'Bangor City']
Norwich City
['CA Bastia', 'Bastia', 'Catania']
SC Bastia
['Cardiff', 'Cork City', 'Bangor City']
Cardiff City
['Oostende', 'Ostersund']
KV Oostende
['Leicester', 'Pelister Bitola', 'Bristol City']
Leicester City
['Boavista', 'Paris FC']
Boavista FC

In [538]:
c

['Neuch\xc3\xa2tel Xamax',
 'FC Z\xc3\xbcrich',
 'Lech Pozna\xc5\x84',
 'AS Nancy-Lorraine',
 'Heart of Midlothian',
 'FC Sochaux-Montb\xc3\xa9liard',
 'Stade Rennais FC',
 'Wis\xc5\x82a Krak\xc3\xb3w',
 '\xc5\x9al\xc4\x85sk Wroc\xc5\x82aw',
 'Girondins de Bordeaux',
 'Arka Gdynia',
 'Olympique Lyonnais',
 'Polonia Bytom',
 'Hamilton Academical FC',
 'FC Bayern Munich',
 'Paris Saint-Germain',
 'FC Energie Cottbus',
 'Inverness Caledonian Thistle',
 'GKS Be\xc5\x82chat\xc3\xb3w',
 'Ruch Chorz\xc3\xb3w',
 'Borussia M\xc3\xb6nchengladbach',
 'Olympique de Marseille',
 'Vit\xc3\xb3ria Guimar\xc3\xa3es',
 'SV Werder Bremen',
 'Hertha BSC Berlin',
 'Royal Excel Mouscron',
 'RAEC Mons',
 'Naval 1\xc2\xb0 de Maio',
 '1. FC K\xc3\xb6ln',
 'Roda JC Kerkrade',
 'N.E.C.',
 'AZ',
 'RC Deportivo de La Coru\xc3\xb1a',
 'Acad\xc3\xa9mica de Coimbra',
 'Vit\xc3\xb3ria Set\xc3\xbabal',
 'Atl\xc3\xa9tico Madrid',
 'Athletic Club de Bilbao',
 'Real Betis Balompi\xc3\xa9',
 'Real Sporting de Gij\xc3\xb3n',
 'Reggio Calabria',
 'Zag\xc5\x82\xc4\x99bie Lubin',
 '1. FC N\xc3\xbcrnberg',
 '1. FSV Mainz 05',
 "US Boulogne Cote D'Opale",
 '"Uni\xc3\xa3o de Leiria, SAD"',
 'Xerez Club Deportivo',
 'Stade Brestois 29',
 '1. FC Kaiserslautern',
 'H\xc3\xa9rcules Club de F\xc3\xbatbol',
 'Oud-Heverlee Leuven',
 'Queens Park Rangers',
 '\xc3\x89vian Thonon Gaillard FC',
 'Stade de Reims',
 'Pogo\xc5\x84 Szczecin',
 'RC Celta de Vigo',
 'SpVgg Greuther F\xc3\xbcrth',
 'Zawisza Bydgoszcz',
 'Partick Thistle F.C.',
 'En Avant de Guingamp',
 'Termalica Bruk-Bet Nieciecza']

In [433]:
all_elo['From']=pd.to_datetime(all_elo['From'])
all_elo['To']=pd.to_datetime(all_elo['To'])

In [ ]:
lis_home=[]
for i in final.index:
    tmp=all_elo[all_elo.Club==final['HomeTeam'][i]]
    lis_home.append(tmp[tmp['To'] >= pd.to_datetime(final.Date[i])].iloc[0]['Elo'])

In [ ]:
lis_away=[]
for i in premier_2017.index:
    tmp=a[a.Club==premier_2017['AwayTeam'][i]]
    lis_away.append(tmp[tmp['To'] >= pd.to_datetime(premier_2017.Date[i])].iloc[0]['Elo'])

In [67]:
final.to_csv('../Data/from_sqlite_Data/Realfinal.csv')

In [68]:
final=pd.read_csv('../Data/from_sqlite_Data/Realfinal.csv')

In [69]:
final.drop(['Unnamed: 0'], axis=1,inplace=True)

In [ ]:
final

# For Betting !

In [278]:
a=pd.read_csv('../Data/premier_legue_old_data/E0_2017.csv')
season=a

In [279]:
#take the columns you care

In [280]:
season=season.iloc[:,1:7]

In [281]:
len(season.HomeTeam.unique())

20

In [282]:
#add the round to be predicted with 0 in all other values

In [283]:
round_to_be_predict=pd.DataFrame(columns=season.columns)

In [284]:
date=pd.to_datetime('28/04/17')

In [285]:
round_to_be_predict.loc[0]=[date,'Southampton','Hull',0,0,'D']
round_to_be_predict.loc[1]=[date,'Stoke','West Ham',0,0,'D']
round_to_be_predict.loc[2]=[date,'Sunderland','Bournemouth',0,0,'D']
round_to_be_predict.loc[3]=[date,'West Brom','Leicester',0,0,'D']
round_to_be_predict.loc[4]=[date,'Crystal Palace','Burnley',0,0,'D']
round_to_be_predict.loc[5]=[date,'Man United','Swansea',0,0,'D']
round_to_be_predict.loc[6]=[date,'Everton','Chelsea',0,0,'D']
round_to_be_predict.loc[7]=[date,'Middlesbrough','Man City',0,0,'D']
round_to_be_predict.loc[8]=[date,'Tottenham','Arsenal',0,0,'D']
round_to_be_predict.loc[9]=[date,'Watford','Liverpool',0,0,'D']

In [286]:
season.tail(n=10)

         Date        HomeTeam        AwayTeam  FTHG  FTAG FTR
324  22/04/17            Hull         Watford     2     0   H
325  22/04/17         Swansea           Stoke     2     0   H
326  22/04/17        West Ham         Everton     0     0   D
327  23/04/17         Burnley      Man United     0     2   A
328  23/04/17       Liverpool  Crystal Palace     1     2   A
329  25/04/17         Chelsea     Southampton     4     2   H
330  26/04/17         Arsenal       Leicester     1     0   H
331  26/04/17  Crystal Palace       Tottenham     0     1   A
332  26/04/17   Middlesbrough      Sunderland     1     0   H
333  27/04/17        Man City      Man United     0     0   D

In [287]:
round_to_be_predict.Date=pd.to_datetime(round_to_be_predict.Date)

In [288]:
season=pd.concat([season,round_to_be_predict]).reset_index()

In [289]:
season.drop('index',axis=1,inplace=True)

In [290]:
season['season']=['2016/2017']*len(season)

In [291]:
teams=season.HomeTeam.unique()
allteamsresults=[]
for i in teams:
    path=pd.DataFrame()            
    path = season[(season["HomeTeam"] == i) | (season['AwayTeam'] == i )] 
    allteamsresults.append(MyDf(path))

In [293]:
for i in range(len(teams)):
    allteamsresults[i].df=calculate_for_team_i(allteamsresults,teams,i)

/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:473: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:477: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:478: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:480: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:481: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:482: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:483: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:484: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:485: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:488: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:490: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:491: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:492: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:496: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:497: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:498: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:501: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:502: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/nicolamacchitella/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:503: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [ ]:
tmp=pd.DataFrame(columns=(
                          'H_ROUND',
    
                          'H_TP3',
                          'H_TP5',
                            
    
                          'H_GS_H', 
                          'H_GS_A', 
                          'H_GR_H', 
                          'H_GR_A', 
                          'H_TGS',
                          'H_TGR', 
                          
                          'H_AvGS_H' ,
                          'H_AvGS_A' ,
                          'H_AvGR_H',
                          'H_AvGR_A',
                          'H_Av_TGS',
                          'H_Av_TGR', 
                          
                          
                          'H_Pnt_H' ,
                          'H_Pnt_A',
                          'H_T_pnt',
                          'H_Av_Pnt_H',
                          'H_Av_pnt_A',
                          'H_Av_T_pnt',
                          
                          'A_ROUND',
    
                          'A_TP3',
                          'A_TP5',

                          'Aw_GS_H', 
                          'Aw_GS_A', 
                          'Aw_GR_H', 
                          'Aw_GR_A', 
                          'Aw_TGS',
                          'Aw_TGR', 
                          
                          'Aw_AvGS_H' ,
                          'Aw_AvGS_A' ,
                          'Aw_AvGR_H',
                          'Aw_AvGR_A',
                          'Aw_Av_TGS',
                          'Aw_Av_TGR', 
                          
                          
                          'Aw_Pnt_H' ,
                          'Aw_Pnt_A',
                          'Aw_T_pnt',
                          'Aw_Av_Pnt_H',
                          'Aw_Av_pnt_A',
                         
                          'Aw_Av_T_pnt',
                          
                          
                          
                         )
                )

In [294]:
allteamsresults[0].df

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,season,Round,T_L3M,T_L5M,GS_H,GS_A,GR_H,GR_A,TGS,TGR,AGS_H,AGS_A,AGR_H,AGR_A,ATGS,ATGR,Pnt_H,Pnt_A,TOTPT,Av_Pnt_H,Av_pnt_A,Av_tot_pnt
0,13/08/16,Burnley,Swansea,0.0,1.0,A,2016/2017,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0.000000,0.000000,0.000000
11,20/08/16,Burnley,Liverpool,2.0,0.0,H,2016/2017,2,0,0,0.0,0.0,1.0,0.0,0.0,1.0,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0,0,0,0.000000,0.000000,0.000000
20,27/08/16,Chelsea,Burnley,3.0,0.0,H,2016/2017,3,3,3,2.0,0.0,1.0,0.0,2.0,1.0,1.000000,0.000000,0.500000,0.000000,1.000000,0.500000,3,0,3,1.500000,0.000000,1.500000
32,10/09/16,Burnley,Hull,1.0,1.0,D,2016/2017,4,0,0,2.0,0.0,1.0,3.0,2.0,4.0,1.000000,0.000000,0.500000,3.000000,0.666667,1.333333,3,0,3,1.500000,0.000000,1.000000
43,17/09/16,Leicester,Burnley,3.0,0.0,H,2016/2017,5,4,1,3.0,0.0,2.0,3.0,3.0,5.0,1.000000,0.000000,0.666667,3.000000,0.750000,1.250000,4,0,4,1.333333,0.000000,1.000000
59,26/09/16,Burnley,Watford,2.0,0.0,H,2016/2017,6,1,0,3.0,0.0,2.0,6.0,3.0,8.0,1.000000,0.000000,0.666667,3.000000,0.600000,1.600000,4,0,4,1.333333,0.000000,0.800000
66,02/10/16,Burnley,Arsenal,0.0,1.0,A,2016/2017,7,4,7,5.0,0.0,2.0,6.0,5.0,8.0,1.250000,0.000000,0.500000,3.000000,0.833333,1.333333,7,0,7,1.750000,0.000000,1.166667
78,16/10/16,Southampton,Burnley,3.0,1.0,H,2016/2017,8,3,4,5.0,0.0,3.0,6.0,5.0,9.0,1.000000,0.000000,0.600000,3.000000,0.714286,1.285714,7,0,7,1.400000,0.000000,1.000000
82,22/10/16,Burnley,Everton,2.0,1.0,H,2016/2017,9,3,4,5.0,1.0,3.0,9.0,6.0,12.0,1.000000,0.333333,0.600000,3.000000,0.750000,1.500000,7,0,7,1.400000,0.000000,0.875000
91,29/10/16,Man United,Burnley,0.0,0.0,D,2016/2017,10,3,6,7.0,1.0,4.0,9.0,8.0,13.0,1.166667,0.333333,0.666667,3.000000,0.888889,1.444444,10,0,10,1.666667,0.000000,1.111111
101,05/11/16,Burnley,Crystal Palace,3.0,2.0,H,2016/2017,11,4,7,7.0,1.0,4.0,9.0,8.0,13.0,1.166667,0.250000,0.666667,2.250000,0.800000,1.300000,10,1,11,1.666667,0.250000,1.100000
119,21/11/16,West Brom,Burnley,4.0,0.0,H,2016/2017,12,7,7,10.0,1.0,6.0,9.0,11.0,15.0,1.428571,0.250000,0.857143,2.250000,1.000000,1.363636,13,1,14,1.857143,0.250000,1.272727
120,26/11/16,Burnley,Man City,1.0,2.0,A,2016/2017,13,4,7,10.0,1.0,6.0,13.0,11.0,19.0,1.428571,0.200000,0.857143,2.600000,0.916667,1.583333,13,1,14,1.857143,0.200000,1.166667
132,03/12/16,Stoke,Burnley,2.0,0.0,H,2016/2017,14,3,7,11.0,1.0,8.0,13.0,12.0,21.0,1.375000,0.200000,1.000000,2.600000,0.923077,1.615385,13,1,14,1.625000,0.200000,1.076923
141,10/12/16,Burnley,Bournemouth,3.0,2.0,H,2016/2017,15,0,4,11.0,1.0,8.0,15.0,12.0,23.0,1.375000,0.166667,1.000000,2.500000,0.857143,1.642857,13,1,14,1.625000,0.166667,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,14/01/17,Burnley,Southampton,1.0,0.0,H,2016/2017,21,6,6,19.0,3.0,11.0,20.0,22.0,31.0,1.727273,0.333333,1.000000,2.222222,1.100000,1.550000,22,1,23,2.000000,0.111111,1.150000
217,22/01/17,Arsenal,Burnley,2.0,1.0,H,2016/2017,22,6,9,20.0,3.0,11.0,20.0,23.0,31.0,1.666667,0.333333,0.916667,2.222222,1.095238,1.476190,25,1,26,2.083333,0.111111,1.238095
222,31/01/17,Burnley,Leicester,1.0,0.0,H,2016/2017,23,3,9,20.0,4.0,11.0,22.0,24.0,33.0,1.666667,0.400000,0.916667,2.200000,1.090909,1.500000,25,1,26,2.083333,0.100000,1.181818
236,04/02/17,Watford,Burnley,2.0,1.0,H,2016/2017,24,6,9,21.0,4.0,11.0,22.0,25.0,33.0,1.615385,0.400000,0.846154,2.200000,1.086957,1.434783,28,1,29,2.153846,0.100000,1.260870
247,12/02/17,Burnley,Chelsea,1.0,1.0,D,2016/2017,25,3,6,21.0,5.0,11.0,24.0,26.0,35.0,1.615385,0.454545,0.846154,2.181818,1.083333,1.458333,28,1,29,2.153846,0.090909,1.208333
253,25/02/17,Hull,Burnley,1.0,1.0,D,2016/2017,26,4,7,22.0,5.0,12.0,24.0,27.0,36.0,1.571429,0.454545,0.857143,2.181818,1.080000,1.440000,29,1,30,2.071429,0.090909,1.200000
262,04/03/17,Swansea,Burnley,3.0,2.0,H,2016/2017,27,2,5,22.0,6.0,12.0,25.0,28.0,37.0,1.571429,0.500000,0.857143,2.083333,1.076923,1.423077,29,2,31,2.071429,0.166667,1.192308
272,12/03/17,Liverpool,Burnley,2.0,1.0,H,2016/2017,28,2,5,22.0,8.0,12.0,28.0,30.0,40.0,1.571429,0.615385,0.857143,2.153846,1.111111,1.481481,29,2,31,2.071429,0.153846,1.148148
277,18/03/17,Sunderland,Burnley,0.0,0.0,D,2016/2017,29,1,2,22.0,9.0,12.0,30.0,31.0,42.0,1.571429,0.642857,0.857143,2.142857,1.107143,1.500000,29,2,31,2.071429,0.142857,1.107143
283,01/04/17,Burnley,Tottenham,0.0,2.0,A,2016/2017,30,1,3,22.0,9.0,12.0,30.0,31.0,42.0,1.571429,0.600000,0.857143,2.000000,1.068966,1.448276,29,3,32,2.071429,0.200000,1.103448
293,04/04/17,Burnley,Stoke,1.0,0.0,H,2016/2017,31,1,2,22.0,9.0,14.0,30.0,31.0,44.0,1.466667,0.600000,0.933333,2.000000,1.033333,1.466667,29,3,32,1.933333,0.200000,1.066667
305,08/04/17,Middlesbrough,Burnley,0.0,0.0,D,2016/2017,32,4,4,23.0,9.0,14.0,30.0,32.0,44.0,1.437500,0.600000,0.875000,2.000000,1.032258,1.419355,32,3,35,2.000000,0.200000,1.129032
314,15/04/17,Everton,Burnley,3.0,1.0,H,2016/2017,33,4,5,23.0,9.0,14.0,30.0,32.0,44.0,1.437500,0.562500,0.875000,1.875000,1.000000,1.375000,32,4,36,2.000000,0.250000,1.125000
327,23/04/17,Burnley,Man United,0.0,2.0,A,2016/2017,34,4,5,23.0,10.0,14.0,33.0,33.0,47.0,1.437500,0.588235,0.875000,1.941176,1.000000,1.424242,32,4,36,2.000000,0.235294,1.090909
338,2017-04-28 00:00:00,Crystal Palace,Burnley,0.0,0.0,D,2016/2017,35,1,4,23.0,10.0,16.0,33.0,33.0,49.0,1.352941,0.588235,0.941176,1.941176,0.970588,1.441176,32,4,36,1.882353,0.235294,1.058824

In [296]:
for i in season.index:
    date=season['Date'][i]
    Home=season['HomeTeam'][i]
    Away=season['AwayTeam'][i]
    
    home_index=pd.Series(teams)[teams==Home].index[0]
    away_index=pd.Series(teams)[teams==Away].index[0]
    tobeappend=list(allteamsresults[home_index].df.loc[i].iloc[7:]) + list(allteamsresults[away_index].df.loc[i].iloc[7:])
    tmp.loc[i]=tobeappend

In [321]:
final=pd.merge(left=season, right=tmp, left_index=True, right_index=True)


final['DIFF_TP']=final['H_T_pnt']-final['Aw_T_pnt']
final['DIFF_HP-AP']=final['H_Pnt_H']-final['Aw_Pnt_A']

final['SUMM_HGSH+HGSH+AGRA']=final['H_GS_H']+final['Aw_GR_A']
final['SUMM_HGRH+AGSA']=final['H_GR_H']+final['Aw_GS_A']
final['SUMM_HTGS+ATGR']=final['H_TGS']+final['Aw_TGR']
final['SUMM_HTGR+ATGS']=final['H_TGR']+final['Aw_TGS']

final['DIFF_L3MP']=final['H_TP3']-final['A_TP3']
final['DIFF_L5MP']=final['H_TP5']-final['A_TP5']


final['DIFF_av_TP']=final['H_Av_T_pnt']-final['Aw_Av_T_pnt']
final['DIFF_av_HP-AP']=final['H_Av_Pnt_H']-final['Aw_Av_pnt_A']

final['SUMM_av_HGSH+AGRA']=final['H_AvGS_H']+final['Aw_AvGR_A']
final['SUMM_av_HGRH+AGSA']=final['H_AvGR_H']+final['Aw_AvGS_A']

final['SUMM_av_HTGS+ATGR']=final['H_Av_TGS']+final['Aw_Av_TGR']
final['SUMM_av_HTGR+ATGS']=final['H_Av_TGR']+final['Aw_Av_TGS']

final['Goal/No_Goal'] = ((final['FTHG']>0 ) * 1)*((final['FTAG']>0) * 1)
final['Over2.5/Under2.5'] = ((final['FTHG'] + final['FTAG']) >2)*1
final['Over1.5/Under1.5'] = ((final['FTHG'] + final['FTAG']) >1)*1

In [331]:
final.to_csv('../Data/from_sqlite_Data/***.csv')